global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using JetBrains.Annotations;
global using UnityEngine;
global using static UnityEngine.Object;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
global using static UnityEngine.ScriptableObject;
global using static ZoneSystem;
global using static JFUtils.ModBase;
global using static ZoneSystem.ZoneLocation;
global using static ZoneSystem.ZoneVegetation;
global using static Heightmap;
global using static Heightmap.Biome;
global using static Skills;
global using static Skills.SkillDef;
global using static UnityEngine.Mathf;