namespace JFUtils
{
    public enum Weather
    {
        ClearSkies,
        MeadowsClearSkies,
        LightRain,
        Rain,
        ThunderStorm,
        ClearThunderStorm,
        SwampRain,
        MistlandsDark,
        AshlandsAshrain,
        MountainSnow,
        MountainBlizzard,
        BlackForestFog,
        Fog,
        DeepNorthSnow,
        DeepNorthSnowStorm,
        DeepNorthClear,
        EikthyrsThunderstorm,
        EldersHaze,
        BonemassDownpour,
        ModersVortex,
        YagluthsMagicBlizzard,
        Crypt,
        SunkenCrypt
    }
}